/*global jQuery:false */
jQuery(document).ready(function($) {
"use strict";

	
		//add some elements with animate effect

		$(".big-cta").hover(
			function () {
			$('.cta a').addClass("animated shake");
			},
			function () {
			$('.cta a').removeClass("animated shake");
			}
		);
		$(".box").hover(
			function () {
			$(this).find('.icon').addClass("animated fadeInDown");
			$(this).find('p').addClass("animated fadeInUp");
			},
			function () {
			$(this).find('.icon').removeClass("animated fadeInDown");
			$(this).find('p').removeClass("animated fadeInUp");
			}
		);
		
		
		$('.accordion').on('show', function (e) {
		
			$(e.target).prev('.accordion-heading').find('.accordion-toggle').addClass('active');
			$(e.target).prev('.accordion-heading').find('.accordion-toggle i').removeClass('icon-plus');
			$(e.target).prev('.accordion-heading').find('.accordion-toggle i').addClass('icon-minus');
		});
		
		$('.accordion').on('hide', function (e) {
			$(this).find('.accordion-toggle').not($(e.target)).removeClass('active');
			$(this).find('.accordion-toggle i').not($(e.target)).removeClass('icon-minus');
			$(this).find('.accordion-toggle i').not($(e.target)).addClass('icon-plus');
		});	

		
		// tooltip
		$('.social-network li a, .options_box .color a').tooltip();

		// fancybox
		$(".fancybox").fancybox({				
				padding : 0,
				autoResize: true,
				beforeShow: function () {
					this.title = $(this.element).attr('title');
					this.title = '<h4>' + this.title + '</h4>' + '<p>' + $(this.element).parent().find('img').attr('alt') + '</p>';
				},
				helpers : {
					title : { type: 'inside' },
				}
			});

		
		//scroll to top
		$(window).scroll(function(){
			if ($(this).scrollTop() > 100) {
				$('.scrollup').fadeIn();
				} else {
				$('.scrollup').fadeOut();
			}
		});
		$('.scrollup').click(function(){
			$("html, body").animate({ scrollTop: 0 }, 1000);
				return false;
		});
    $('#post-slider').flexslider({
        // Primary Controls
        controlNav          : false,              //Boolean: Create navigation for paging control of each clide? Note: Leave true for manualControls usage
        directionNav        : true,              //Boolean: Create navigation for previous/next navigation? (true/false)
        prevText            : "Previous",        //String: Set the text for the "previous" directionNav item
        nextText            : "Next",            //String: Set the text for the "next" directionNav item
         
        // Secondary Navigation
        keyboard            : true,              //Boolean: Allow slider navigating via keyboard left/right keys
        multipleKeyboard    : false,             //{NEW} Boolean: Allow keyboard navigation to affect multiple sliders. Default behavior cuts out keyboard navigation with more than one slider present.
        mousewheel          : false,             //{UPDATED} Boolean: Requires jquery.mousewheel.js (https://github.com/brandonaaron/jquery-mousewheel) - Allows slider navigating via mousewheel
        pausePlay           : false,             //Boolean: Create pause/play dynamic element
        pauseText           : 'Pause',           //String: Set the text for the "pause" pausePlay item
        playText            : 'Play',            //String: Set the text for the "play" pausePlay item
         
        // Special properties
        controlsContainer   : "",                //{UPDATED} Selector: USE CLASS SELECTOR. Declare which container the navigation elements should be appended too. Default container is the FlexSlider element. Example use would be ".flexslider-container". Property is ignored if given element is not found.
        manualControls      : "",                //Selector: Declare custom control navigation. Examples would be ".flex-control-nav li" or "#tabs-nav li img", etc. The number of elements in your controlNav should match the number of slides/tabs.
        sync                : "",                //{NEW} Selector: Mirror the actions performed on this slider with another slider. Use with care.
        asNavFor            : "",                //{NEW} Selector: Internal property exposed for turning the slider into a thumbnail navigation for another slider
    });
	
    $('#main-slider').flexslider({
        namespace           : "flex-",           //{NEW} String: Prefix string attached to the class of every element generated by the plugin
        selector            : ".slides > li",    //{NEW} Selector: Must match a simple pattern. '{container} > {slide}' -- Ignore pattern at your own peril
        animation           : "fade",            //String: Select your animation type, "fade" or "slide"
        easing              : "swing",           //{NEW} String: Determines the easing method used in jQuery transitions. jQuery easing plugin is supported!
        direction           : "horizontal",      //String: Select the sliding direction, "horizontal" or "vertical"
        reverse             : false,             //{NEW} Boolean: Reverse the animation direction
        animationLoop       : true,              //Boolean: Should the animation loop? If false, directionNav will received "disable" classes at either end
        smoothHeight        : false,             //{NEW} Boolean: Allow height of the slider to animate smoothly in horizontal mode
        startAt             : 0,                 //Integer: The slide that the slider should start on. Array notation (0 = first slide)
        slideshow           : true,              //Boolean: Animate slider automatically
        slideshowSpeed      : 7000,              //Integer: Set the speed of the slideshow cycling, in milliseconds
        animationSpeed      : 600,               //Integer: Set the speed of animations, in milliseconds
        initDelay           : 0,                 //{NEW} Integer: Set an initialization delay, in milliseconds
        randomize           : false,             //Boolean: Randomize slide order
         
        // Usability features
        pauseOnAction       : true,              //Boolean: Pause the slideshow when interacting with control elements, highly recommended.
        pauseOnHover        : false,             //Boolean: Pause the slideshow when hovering over slider, then resume when no longer hovering
        useCSS              : true,              //{NEW} Boolean: Slider will use CSS3 transitions if available
        touch               : true,              //{NEW} Boolean: Allow touch swipe navigation of the slider on touch-enabled devices
        video               : false,             //{NEW} Boolean: If using video in the slider, will prevent CSS3 3D Transforms to avoid graphical glitches
         
        // Primary Controls
        controlNav          : true,              //Boolean: Create navigation for paging control of each clide? Note: Leave true for manualControls usage
        directionNav        : true,              //Boolean: Create navigation for previous/next navigation? (true/false)
        prevText            : "Previous",        //String: Set the text for the "previous" directionNav item
        nextText            : "Next",            //String: Set the text for the "next" directionNav item
         
        // Secondary Navigation
        keyboard            : true,              //Boolean: Allow slider navigating via keyboard left/right keys
        multipleKeyboard    : false,             //{NEW} Boolean: Allow keyboard navigation to affect multiple sliders. Default behavior cuts out keyboard navigation with more than one slider present.
        mousewheel          : false,             //{UPDATED} Boolean: Requires jquery.mousewheel.js (https://github.com/brandonaaron/jquery-mousewheel) - Allows slider navigating via mousewheel
        pausePlay           : false,             //Boolean: Create pause/play dynamic element
        pauseText           : 'Pause',           //String: Set the text for the "pause" pausePlay item
        playText            : 'Play',            //String: Set the text for the "play" pausePlay item
         
        // Special properties
        controlsContainer   : "",                //{UPDATED} Selector: USE CLASS SELECTOR. Declare which container the navigation elements should be appended too. Default container is the FlexSlider element. Example use would be ".flexslider-container". Property is ignored if given element is not found.
        manualControls      : "",                //Selector: Declare custom control navigation. Examples would be ".flex-control-nav li" or "#tabs-nav li img", etc. The number of elements in your controlNav should match the number of slides/tabs.
        sync                : "",                //{NEW} Selector: Mirror the actions performed on this slider with another slider. Use with care.
        asNavFor            : "",                //{NEW} Selector: Internal property exposed for turning the slider into a thumbnail navigation for another slider
    });
    // Dark mode toggle (persisted with localStorage)
    function applyDarkMode(isOn){
      if(isOn){
        $('body').addClass('dark-mode');
        $('#darkModeToggle').attr('aria-pressed','true').find('i').removeClass('fa-moon-o').addClass('fa-sun-o');
      } else {
        $('body').removeClass('dark-mode');
        $('#darkModeToggle').attr('aria-pressed','false').find('i').removeClass('fa-sun-o').addClass('fa-moon-o');
      }
    }
    var dark = (localStorage.getItem('darkMode') === 'on');
    // Apply saved preference on all pages (even if toggle isn't present) so theme is consistent across the site
    applyDarkMode(dark);

    // Toggle behavior
    $('#darkModeToggle').on('click', function(e){
      e.preventDefault();
      dark = !$('body').hasClass('dark-mode');
      applyDarkMode(dark);
      localStorage.setItem('darkMode', dark ? 'on' : 'off');
    });

    // Keyboard shortcut: press 'd' to toggle dark mode (accessibility + convenience)
    $(document).on('keydown', function(e){
      if(e.key === 'd' || e.key === 'D'){
        dark = !$('body').hasClass('dark-mode');
        applyDarkMode(dark);
        localStorage.setItem('darkMode', dark ? 'on' : 'off');
      }
    });

    /* --------- Simple Sign In UI (client-side demo) --------- */
    function renderSignInModal(){
      if($('#signInModal').length) return;
      var modal = `
      <div class="modal fade" id="signInModal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-sm">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">&times;</button>
              <h4 class="modal-title">Sign In</h4>
            </div>
            <div class="modal-body">
              <form id="signInForm">
                <div class="form-group">
                  <label for="signinName">Name</label>
                  <input type="text" id="signinName" class="form-control" placeholder="Your name">
                </div>
                <div class="form-group">
                  <label for="signinEmail">Email</label>
                  <input type="email" id="signinEmail" class="form-control" placeholder="you@example.com" required>
                </div>
                <div class="form-group">
                  <label for="signinPass">Password</label>
                  <input type="password" id="signinPass" class="form-control" placeholder="Password" required>
                </div>
                <button type="submit" class="btn btn-primary btn-block">Sign In</button>
              </form>
              <p class="text-center" style="margin-top:8px;"><small>This is a demo sign-in (no server). Your name is stored locally.</small></p>
            </div>
          </div>
        </div>
      </div>`;
      $('body').append(modal);
    }

    function escapeHtml(text){ return $('<div>').text(text).html(); }

    function updateAuthUI(){
      var user = localStorage.getItem('kflk_user');
      if(user){
        $('#auth-area').html('<a href="#" id="accountBtn">Hi, '+escapeHtml(user)+'</a> <a href="#" id="logoutBtn" class="ml-2">Logout</a>');
      } else {
        $('#auth-area').html('<a href="#" id="signInBtn">Sign In</a>');
      }
    }

    // Render modal and wire up handlers
    renderSignInModal();
    updateAuthUI();

    // Open modal
    $(document).on('click','#signInBtn', function(e){ e.preventDefault(); $('#signInModal').modal('show'); });

    // Submit sign-in (client-side demo)
    $(document).on('submit','#signInForm', function(e){
      e.preventDefault();
      var name = $('#signinName').val().trim();
      var email = $('#signinEmail').val().trim();
      if(!email){ alert('Please enter your email.'); return; }
      if(!name) name = email.split('@')[0];
      localStorage.setItem('kflk_user', name);
      updateAuthUI();
      $('#signInModal').modal('hide');
    });

    // Logout
    $(document).on('click','#logoutBtn', function(e){ e.preventDefault(); localStorage.removeItem('kflk_user'); updateAuthUI(); });

});